services:
  db:
    hostname: db
    image: ankane/pgvector
    ports:
      - 6543:5432
    restart: always
    environment:
      - POSTGRES_DB=paralegal_ai_local
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017